# Generated by Django 3.2.8 on 2021-10-21 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True,
                                                    on_delete=django.db.models.deletion.CASCADE,
                                                    parent_link=True,
                                                    primary_key=True,
                                                    serialize=False,
                                                    to='school.person')),
            ],
            bases=('school.person',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True,
                                                    on_delete=django.db.models.deletion.CASCADE,
                                                    parent_link=True,
                                                    primary_key=True,
                                                    serialize=False,
                                                    to='school.person')),
            ],
            bases=('school.person',),
        ),
        migrations.CreateModel(
            name='HomeworkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('completed_date', models.DateTimeField()),
                ('solution', models.CharField(max_length=100)),
                ('homework', models.ForeignKey(null=True,
                                               on_delete=django.db.models.deletion.SET_NULL,
                                               to='school.homework')),
                ('student', models.ForeignKey(null=True,
                                              on_delete=django.db.models.deletion.SET_NULL,
                                              to='school.student')),
                ('teacher', models.ForeignKey(null=True,
                                              on_delete=django.db.models.deletion.SET_NULL,
                                              to='school.teacher')),
            ],
        ),
    ]
